# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: pose_estimation_sample
description: Demonstrates pose estimation with YOLO
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ultralytics_yolo:
    path: ../../
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
